sudo: required
services:
  - docker
language: python
python:
  - '2.7'
cache:
  directories:
    - "$HOME/.cache/pip"
git:
  depth: 3
branches:
  only:
    - master
env:
  global:
    - SKIP_CLEANUP=true
    - PIP_CACHE=$HOME/.cache/pip
<<<<<<< HEAD
    - SDK_TESTING=true
    - BUNDLE_PATH=$TRAVIS_BUILD_DIR/vendor/cache
    - DD_AGENT_BRANCH=master
    - CORE_BRANCH=master
    - JMXFETCH_URL="https://dd-jmxfetch.s3.amazonaws.com"
    - REQ_LOCALS="$TRAVIS_BUILD_DIR,$HOME/dd-agent,$HOME/integrations-core"
  matrix:
    - TRAVIS_FLAVOR=default
    - TRAVIS_FLAVOR=filebeat FLAVOR_VERSION=latest
    - TRAVIS_FLAVOR=snmpwalk
    - TRAVIS_FLAVOR=hbase_master
    - TRAVIS_FLAVOR=hbase_regionserver
    - TRAVIS_FLAVOR=redis_sentinel FLAVOR_VERSION="latest"
    - TRAVIS_FLAVOR=neo4j
    - TRAVIS_FLAVOR=storm FLAVOR_VERSION=latest
    - TRAVIS_FLAVOR=logstash FLAVOR_VERSION=latest
    - TRAVIS_FLAVOR=stardog FLAVOR_VERSION=latest
    - TRAVIS_FLAVOR=reboot_required FLAVOR_VERSION=latest
    - TRAVIS_FLAVOR=upsc FLAVOR_VERSION=latest
    - TRAVIS_FLAVOR=gnatsd_streaming FLAVOR_VERSION=latest
    - TRAVIS_FLAVOR=aerospike FLAVOR_VERSION=latest
    - TRAVIS_FLAVOR=gnatsd FLAVOR_VERSION=latest
=======
    - TRAVIS_FLAVOR=portworx FLAVOR_VERSION=latest
    - TRAVIS_FLAVOR=gnatsd FLAVOR_VERSION=latest
>>>>>>> 01aabcdb7fa7125ae229935e8de2a081b38cd839
    # END OF TRAVIS MATRIX
=======
>>>>>>> 5298fc485e90c4342449c53c00cb4509524ca9d3

stages:
  - name: test_changed
    if: type = pull_request
  - name: test
    if: (branch = master) AND (type != pull_request)

script: travis_retry inv test --targets=${CHECK}

# Conditional jobs are currently buggy and verbose.
#
# https://github.com/travis-ci/beta-features/issues/28
# https://github.com/travis-ci/beta-features/issues/40
# https://github.com/travis-ci/travis-ci/issues/8295
# https://github.com/travis-ci/travis-conditions/pull/1
# https://github.com/travis-ci/travis-ci/issues/6652
jobs:
  fast_finish: true
  include:
    - stage: test_changed
      script:
       #  - inv manifest --include-extras FIXME: re-enable as soon as we fix the manifest files
       - inv test --changed-only
    - stage: test
      env: CHECK=reboot_required
      script:
        # - inv manifest --include-extras FIXME: re-enable as soon as we fix the manifest files
        - travis_retry inv test --targets=${CHECK}
    - stage: test
      env: CHECK=sortdb
      script:
        # - inv manifest --include-extras FIXME: re-enable as soon as we fix the manifest files
        - travis_retry inv test --targets=${CHECK}

install:
  - pip install -U pip setuptools
  - pip install -r requirements-dev.txt

# we should clean generated files before we save the cache
# We don't want to save .pyc files, so we'll use find and -delete
before_cache:
  - find $HOME/.cache/pip -name *.pyc -delete
