steps:

- script: ddev validate config
  displayName: 'Validate default configuration files'

- script: ddev validate manifest -i
  displayName: 'Validate manifest files'

- script: ddev validate metadata
  displayName: 'Validate metric data'

- script: ddev validate service-checks
  displayName: 'Validate service check data'
