jobs:
  - template: "./test-single-linux.yml"
    parameters:
      check: aerospike
      display: Aerospike
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: ambassador
      display: Ambassador
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: apollo_engine
      display: Apollo Engine
      validate: true

  - template: "./test-single-windows.yml"
    parameters:
      check: aqua
      display: Aqua
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: aws_pricing
      display: AWS Pricing
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: bind9
      display: Bind9
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: bluematador
      display: Bluematador
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: bonsai
      display: Bonsai
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: buddy
      display: Buddy
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: concourse_ci
      display: Concourse CI
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: convox
      display: Convox
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: eventstore
      display: EventStore
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: filebeat
      display: Filebeat
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: gnatsd
      display: Gnatsd
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: gnatsd_streaming
      display: Gnatsd Streaming
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: gremlin
      display: Gremlin
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: hbase_master
      display: HBase-master
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: hbase_regionserver
      display: HBase-regionserver
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: launchdarkly
      display: LaunchDarkly
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: lighthouse
      display: Lighthouse
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: logstash
      display: Logstash
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: logzio
      display: Logzio
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: neo4j
      display: Neo4j
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: neutrona
      display: Neutrona
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: nextcloud
      display: Nextcloud
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: nomad
      display: Nomad
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: ping
      display: Ping
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: portworx
      display: Portworx
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: rbltracker
      display: Rbltracker
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: reboot_required
      display: Reboot Required
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: redis_sentinel
      display: Redis sentinel
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: riak_repl
      display: Riak repl
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: rigor
      display: Rigor
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: rookout
      display: Rookout
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: sendmail
      display: Sendmail
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: sigsci
      display: Signal sciences
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: snmpwalk
      display: Snmpwalk
      validate: true

  - template: "./test-single-windows.yml"
    parameters:
      check: sortdb
      display: Sortdb
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: split
      display: Split
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: stardog
      display: Stardog
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: storm
      display: Storm
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: traefik
      display: Traefik
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: unbound
      display: Unbound
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: upsc
      display: Upsc
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: uptime
      display: Uptime
      validate: true

  - template: "./test-single-linux.yml"
    parameters:
      check: vns3
      display: VNS3
      validate: true
