schedules:
- cron: "0 5 * * *"
  displayName: Nightly (EDT/EST)
  always: true
  branches:
    include:
    - master

trigger: none
# Re-enable when we have enough runners
# trigger:
#   branches:
#     include:
#     - master

pr:
  branches:
    include:
    - master

variables:
  DDEV_COLOR: 1

jobs:
- template: './templates/test-all.yml'
