trigger: none

pr:
  branches:
    include:
    - master

variables:
  DDEV_COLOR: 1

jobs:
- template: './templates/test-single-linux.yml'
  parameters:
    job_name: Changed
    display: Linux
    validate: true

- template: './templates/test-single-windows.yml'
  parameters:
    job_name: Changed
    check: '--changed none_yet'
    display: Windows
